# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [1]:
import numpy as np

In [5]:
# ==============================================================================
# EJERCICIOS RESUELTOS DE NUMPY - ACTIVIDAD 2
# ==============================================================================

print("--- EJERCICIO 1 ---")
a1 = np.array([1, 2, 3, 4])
print("¿Ninguno es cero?:", np.all(a1 != 0))

print("\n--- EJERCICIO 2 ---")
a2 = np.array([0, 0, 2, 0])
print("¿Contiene algún elemento no cero?:", np.any(a2 != 0))

print("\n--- EJERCICIO 3 ---")
a3 = np.array([1, 2, np.nan, np.inf])
print("Valores infinitos o NaN:", np.isinf(a3) | np.isnan(a3))

print("\n--- EJERCICIO 4 ---")
a4 = np.array([1, 2, np.inf])
print("¿Contiene valores infinitos?:", np.isinf(a4).any())

print("\n--- EJERCICIO 5 ---")
a5 = np.array([1, np.nan, 3])
print("¿Contiene valores NaN?:", np.isnan(a5).any())

print("\n--- EJERCICIO 6 ---")
a6 = np.array([1, 3, 51])
b6 = np.array([2, 3, 4])
print("a > b :", a6 > b6)
print("a >= b:", a6 >= b6)
print("a < b :", a6 < b6)
print("a <= b:", a6 <= b6)

print("\n--- EJERCICIO 7 ---")
a7 = np.array([1, 7, 13, 106])
print("Memoria ocupada (bytes):", a7.nbytes)

print("\n--- EJERCICIO 8 ---")
a8 = np.concatenate([np.zeros(10), np.ones(10), np.ones(10) * 5])
print("Arreglo 10 ceros, 10 unos, 10 cincos:\n", a8)

print("\n--- EJERCICIO 9 ---")
a9 = np.arange(30, 71)
print("Enteros entre 30 y 70:\n", a9)

print("\n--- EJERCICIO 10 ---")
a10 = np.arange(30, 71, 2)
print("Pares entre 30 y 70:\n", a10)

print("\n--- EJERCICIO 11 ---")
matriz_id = np.eye(3)
print("Matriz identidad de 3x3:\n", matriz_id)

print("\n--- EJERCICIO 12 ---")
aleatorio = np.random.rand()
print("Número aleatorio entre 0 y 1:", aleatorio)

print("\n--- EJERCICIO 13 ---")
normal = np.random.randn(15)
print("15 números de distribución normal estándar:\n", normal)

print("\n--- EJERCICIO 14 ---")
a14 = np.arange(15, 56)
print("Valores excepto el primero y el último:\n", a14[1:-1])

print("\n--- EJERCICIO 15 ---")
a15 = np.linspace(5, 50, 10)
print("Vector longitud 10 equitativamente distribuido:\n", a15)

print("\n--- EJERCICIO 16 ---")
v16 = np.arange(0, 21)
v16[(v16 >= 9) & (v16 <= 15)] *= -1
print("Signo cambiado de 9 a 15:\n", v16)

print("\n--- EJERCICIO 17 ---")
a17 = np.array([1, 2, 3])
lista17 = a17.tolist()
print("Convertido a lista de Python:", lista17, type(lista17))

print("\n--- EJERCICIO 18 ---")
L18 = [1, 2, 3]
a18 = np.array(L18)
print("Lista convertida a arreglo NumPy:", a18, type(a18))

print("\n--- EJERCICIO 19 ---")
m19 = np.array([[1, 2], [3, 4]])
pares19 = np.where(m19 % 2 == 0, m19, 0)
print("Matriz original:\n", m19)
print("Matriz solo con números pares:\n", pares19)

print("\n--- EJERCICIO 20 ---")
m20 = np.array([[1, 2, 3], [4, 5, 6]])
filas, columnas = m20.shape
print(f"Número de filas: {filas}")
print(f"Número de columnas: {columnas}")


--- EJERCICIO 1 ---
¿Ninguno es cero?: True

--- EJERCICIO 2 ---
¿Contiene algún elemento no cero?: True

--- EJERCICIO 3 ---
Valores infinitos o NaN: [False False  True  True]

--- EJERCICIO 4 ---
¿Contiene valores infinitos?: True

--- EJERCICIO 5 ---
¿Contiene valores NaN?: True

--- EJERCICIO 6 ---
a > b : [False False  True]
a >= b: [False  True  True]
a < b : [ True False False]
a <= b: [ True  True False]

--- EJERCICIO 7 ---
Memoria ocupada (bytes): 32

--- EJERCICIO 8 ---
Arreglo 10 ceros, 10 unos, 10 cincos:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]

--- EJERCICIO 9 ---
Enteros entre 30 y 70:
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]

--- EJERCICIO 10 ---
Pares entre 30 y 70:
 [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]

--- EJERCICIO 11 ---
Matriz identidad de 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

--- EJERCICIO 12